# Generated by Django 5.0.6 on 2024-07-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
