# Generated by Django 5.0.6 on 2024-07-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
    ]
